@host = http://localhost:5002

### ---------- BankAccount ----------
GET {{host}}/api/bank-accounts

###
POST {{host}}/api/bank-accounts
Content-Type: application/json

{ "accountNo": "TR01", "accountStatus": "Active", "balance": 1000.00 }

###
GET {{host}}/api/bank-accounts/TR01

###
# Bakiye değişmez, sadece durum güncellenir
PUT {{host}}/api/bank-accounts/TR01
Content-Type: application/json

{ "accountNo": "TR01", "accountStatus": "Blocked", "balance": 999999 }

###
DELETE {{host}}/api/bank-accounts/TR01

### ---------- Card ----------
GET {{host}}/api/cards

###
POST {{host}}/api/cards
Content-Type: application/json

{
  "cardNumber": "4111111111111111",
  "accountNo": "TR01",
  "cardType": "Debit",
  "expiryDate": "1228",
  "contactlessAllowed": true,
  "contactlessLimit": 750.00
}

###
GET {{host}}/api/cards/by-number/4111111111111111

###
PUT {{host}}/api/cards/1
Content-Type: application/json

{
  "cardNumber": "4111111111111111",
  "accountNo": "TR01",
  "cardType": "Credit",
  "expiryDate": "1229",
  "contactlessAllowed": false
}

###
DELETE {{host}}/api/cards/1

### ---------- TransactionType (Otc/Ots) ----------
GET {{host}}/api/transaction-types

###
GET {{host}}/api/transaction-types/10/11

###
POST {{host}}/api/transaction-types
Content-Type: application/json

{ "otc": "20", "ots": "11", "name": "Refund" }

###
PUT {{host}}/api/transaction-types/20/11
Content-Type: application/json

{ "otc": "20", "ots": "11", "name": "Return" }

###
DELETE {{host}}/api/transaction-types/20/11

### ---------- MtiProcessingCode (MTI + F3) ----------
GET {{host}}/api/mti-processing-codes

###
GET {{host}}/api/mti-processing-codes/0200/000000

###
POST {{host}}/api/mti-processing-codes
Content-Type: application/json

{ "mti": "0200", "f3_ProcessingCode": "200000", "otc": "20", "ots": "11" }

###
PUT {{host}}/api/mti-processing-codes/0200/200000
Content-Type: application/json

{ "mti": "0200", "f3_ProcessingCode": "200000", "otc": "10", "ots": "11" }

###
DELETE {{host}}/api/mti-processing-codes/0200/200000
